### ISSUE TITLE
Tests fail with Python 3

### ISSUE THREAD

**Issue by sbraz** [jelmer/dulwich#422]
Hi, I see three failures which look like they are related to unicode handling. They are present on both Python 3.4 and 3.5.
```

======================================================================
ERROR: test_finder (dulwich.tests.test_greenthreads.TestGreenThreadsMissingObjectFinder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 121, in setUp
    self.objs = init_store(self.store, self.cmt_amount)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 70, in init_store
    objs = create_commit(marker=i)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 54, in create_commit
    blob = Blob.from_string('The blob content %s' % marker)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 421, in from_string
    obj.set_raw_string(string)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 311, in set_raw_string
    raise TypeError('Expected bytes for text, got %r' % text)
TypeError: Expected bytes for text, got 'The blob content 0'

======================================================================
ERROR: test_iter (dulwich.tests.test_greenthreads.TestGreenThreadsObjectStoreIterator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 84, in setUp
    self.objs = init_store(self.store, self.cmt_amount)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 70, in init_store
    objs = create_commit(marker=i)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 54, in create_commit
    blob = Blob.from_string('The blob content %s' % marker)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 421, in from_string
    obj.set_raw_string(string)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 311, in set_raw_string
    raise TypeError('Expected bytes for text, got %r' % text)
TypeError: Expected bytes for text, got 'The blob content 0'

======================================================================
ERROR: test_len (dulwich.tests.test_greenthreads.TestGreenThreadsObjectStoreIterator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 84, in setUp
    self.objs = init_store(self.store, self.cmt_amount)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 70, in init_store
    objs = create_commit(marker=i)
  File "/home/sbraz/dulwich-0.13.0/dulwich/tests/test_greenthreads.py", line 54, in create_commit
    blob = Blob.from_string('The blob content %s' % marker)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 421, in from_string
    obj.set_raw_string(string)
  File "/home/sbraz/dulwich-0.13.0/dulwich/objects.py", line 311, in set_raw_string
    raise TypeError('Expected bytes for text, got %r' % text)
TypeError: Expected bytes for text, got 'The blob content 0'

----------------------------------------------------------------------
Ran 1056 tests in 62.809s

FAILED (errors=3, skipped=70)

```

**Comment by jelmer** [comment]
On Sun, Apr 24, 2016 at 01:58:58PM -0700, Louis Sautier wrote:
> Hi, I see three failures which look like they are related to unicode handling. They are present on both Python 3.4 and 3.5.
Thanks for reporting. I've pushed a fix to master.

Jelmer

**Comment by sbraz** [comment]
Thanks! By the way, I see that you don't test gevent with Python 3? isn't it supposed to work with recent versions?

**Comment by jelmer** [comment]
On Sun, Apr 24, 2016 at 02:29:41PM -0700, Louis Sautier wrote:
> Thanks! By the way, I see that you don't test gevent with Python 3? isn't it supposed to work with recent versions?
Testing with gevent in travis with python3 was enabled in the commit
that fixed this bug.

**Comment by sbraz** [comment]
It's still not included here though, right? https://github.com/jelmer/dulwich/blob/master/setup.py#L49

**Comment by jelmer** [comment]
On Sun, Apr 24, 2016 at 02:57:42PM -0700, Louis Sautier wrote:
> It's still not included here though, right? https://github.com/jelmer/dulwich/blob/master/setup.py#L49
Ah, I see what you mean. I don't personally use setuptools myself.
Fixed now.
